# Template PHP Build

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

image: composer:2.0


pipelines:
  default:
    - parallel:
        - step:
            name: Test
            script:
              - composer install
              - cp .env.example .env
              - php artisan key:generate
              - php artisan test
            caches:
              - composer

        - step:
          name: codestyle
          cache: {} #override with an empty object.
          script:
            - phpcs --standard=PSR2 --extensions=php app

  cache:
  #We key the cache using the branch's unique identifier.
    key: ${CI_COMMIT_REF_SLUG}

    paths:
      #we only want to cache the vendor folder
      - vendor/


