# Template PHP Build

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

image: composer:2.0


pipelines:
  default:
    - parallel:
        - step:
            name: Test
            script:
              - composer install
              - cp .env.example .env
              - php artisan key:generate
              - php artisan test
            caches:
              - composer
        - step:
            name: codestyle
            script:
              - phpcs --standard=PSR2 --extensions=php app



